// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: api/scheduler/v1/scheduler.proto

package schedulerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GiveUpReason int32

const (
	GiveUpReason_GIVE_UP_REASON_UNSPECIFIED       GiveUpReason = 0
	GiveUpReason_GIVE_UP_REASON_CANCELED          GiveUpReason = 1
	GiveUpReason_GIVE_UP_REASON_BUDGET_EXPIRED    GiveUpReason = 2
	GiveUpReason_GIVE_UP_REASON_RERANKS_EXHAUSTED GiveUpReason = 3
)

// Enum value maps for GiveUpReason.
var (
	GiveUpReason_name = map[int32]string{
		0: "GIVE_UP_REASON_UNSPECIFIED",
		1: "GIVE_UP_REASON_CANCELED",
		2: "GIVE_UP_REASON_BUDGET_EXPIRED",
		3: "GIVE_UP_REASON_RERANKS_EXHAUSTED",
	}
	GiveUpReason_value = map[string]int32{
		"GIVE_UP_REASON_UNSPECIFIED":       0,
		"GIVE_UP_REASON_CANCELED":          1,
		"GIVE_UP_REASON_BUDGET_EXPIRED":    2,
		"GIVE_UP_REASON_RERANKS_EXHAUSTED": 3,
	}
)

func (x GiveUpReason) Enum() *GiveUpReason {
	p := new(GiveUpReason)
	*p = x
	return p
}

func (x GiveUpReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GiveUpReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_scheduler_v1_scheduler_proto_enumTypes[0].Descriptor()
}

func (GiveUpReason) Type() protoreflect.EnumType {
	return &file_api_scheduler_v1_scheduler_proto_enumTypes[0]
}

func (x GiveUpReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GiveUpReason.Descriptor instead.
func (GiveUpReason) EnumDescriptor() ([]byte, []int) {
	return file_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

type TerminalProof int32

const (
	TerminalProof_TERMINAL_PROOF_UNSPECIFIED     TerminalProof = 0
	TerminalProof_TERMINAL_PROOF_PROVIDER_FINISH TerminalProof = 1
	TerminalProof_TERMINAL_PROOF_NOT_SENT        TerminalProof = 2
)

// Enum value maps for TerminalProof.
var (
	TerminalProof_name = map[int32]string{
		0: "TERMINAL_PROOF_UNSPECIFIED",
		1: "TERMINAL_PROOF_PROVIDER_FINISH",
		2: "TERMINAL_PROOF_NOT_SENT",
	}
	TerminalProof_value = map[string]int32{
		"TERMINAL_PROOF_UNSPECIFIED":     0,
		"TERMINAL_PROOF_PROVIDER_FINISH": 1,
		"TERMINAL_PROOF_NOT_SENT":        2,
	}
)

func (x TerminalProof) Enum() *TerminalProof {
	p := new(TerminalProof)
	*p = x
	return p
}

func (x TerminalProof) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerminalProof) Descriptor() protoreflect.EnumDescriptor {
	return file_api_scheduler_v1_scheduler_proto_enumTypes[1].Descriptor()
}

func (TerminalProof) Type() protoreflect.EnumType {
	return &file_api_scheduler_v1_scheduler_proto_enumTypes[1]
}

func (x TerminalProof) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerminalProof.Descriptor instead.
func (TerminalProof) EnumDescriptor() ([]byte, []int) {
	return file_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

type AmbiguousCause int32

const (
	AmbiguousCause_AMBIGUOUS_CAUSE_UNSPECIFIED AmbiguousCause = 0
	AmbiguousCause_AMBIGUOUS_CAUSE_TRANSPORT   AmbiguousCause = 1
	AmbiguousCause_AMBIGUOUS_CAUSE_CANCELED    AmbiguousCause = 2
	AmbiguousCause_AMBIGUOUS_CAUSE_PROTOCOL    AmbiguousCause = 3
)

// Enum value maps for AmbiguousCause.
var (
	AmbiguousCause_name = map[int32]string{
		0: "AMBIGUOUS_CAUSE_UNSPECIFIED",
		1: "AMBIGUOUS_CAUSE_TRANSPORT",
		2: "AMBIGUOUS_CAUSE_CANCELED",
		3: "AMBIGUOUS_CAUSE_PROTOCOL",
	}
	AmbiguousCause_value = map[string]int32{
		"AMBIGUOUS_CAUSE_UNSPECIFIED": 0,
		"AMBIGUOUS_CAUSE_TRANSPORT":   1,
		"AMBIGUOUS_CAUSE_CANCELED":    2,
		"AMBIGUOUS_CAUSE_PROTOCOL":    3,
	}
)

func (x AmbiguousCause) Enum() *AmbiguousCause {
	p := new(AmbiguousCause)
	*p = x
	return p
}

func (x AmbiguousCause) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AmbiguousCause) Descriptor() protoreflect.EnumDescriptor {
	return file_api_scheduler_v1_scheduler_proto_enumTypes[2].Descriptor()
}

func (AmbiguousCause) Type() protoreflect.EnumType {
	return &file_api_scheduler_v1_scheduler_proto_enumTypes[2]
}

func (x AmbiguousCause) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AmbiguousCause.Descriptor instead.
func (AmbiguousCause) EnumDescriptor() ([]byte, []int) {
	return file_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

type IdempotencyLookupCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PepperVersion uint32                 `protobuf:"varint,1,opt,name=pepper_version,json=pepperVersion,proto3" json:"pepper_version,omitempty"`
	HmacSha256    []byte                 `protobuf:"bytes,2,opt,name=hmac_sha256,json=hmacSha256,proto3" json:"hmac_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdempotencyLookupCandidate) Reset() {
	*x = IdempotencyLookupCandidate{}
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdempotencyLookupCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdempotencyLookupCandidate) ProtoMessage() {}

func (x *IdempotencyLookupCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdempotencyLookupCandidate.ProtoReflect.Descriptor instead.
func (*IdempotencyLookupCandidate) Descriptor() ([]byte, []int) {
	return file_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *IdempotencyLookupCandidate) GetPepperVersion() uint32 {
	if x != nil {
		return x.PepperVersion
	}
	return 0
}

func (x *IdempotencyLookupCandidate) GetHmacSha256() []byte {
	if x != nil {
		return x.HmacSha256
	}
	return nil
}

type RequestDigestCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DigestVersion uint32                 `protobuf:"varint,1,opt,name=digest_version,json=digestVersion,proto3" json:"digest_version,omitempty"`
	HmacSha256    []byte                 `protobuf:"bytes,2,opt,name=hmac_sha256,json=hmacSha256,proto3" json:"hmac_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDigestCandidate) Reset() {
	*x = RequestDigestCandidate{}
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDigestCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDigestCandidate) ProtoMessage() {}

func (x *RequestDigestCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDigestCandidate.ProtoReflect.Descriptor instead.
func (*RequestDigestCandidate) Descriptor() ([]byte, []int) {
	return file_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *RequestDigestCandidate) GetDigestVersion() uint32 {
	if x != nil {
		return x.DigestVersion
	}
	return 0
}

func (x *RequestDigestCandidate) GetHmacSha256() []byte {
	if x != nil {
		return x.HmacSha256
	}
	return nil
}

type ScheduleRequest struct {
	state                       protoimpl.MessageState        `protogen:"open.v1"`
	RequestId                   string                        `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AttemptId                   string                        `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	TenantScope                 []byte                        `protobuf:"bytes,3,opt,name=tenant_scope,json=tenantScope,proto3" json:"tenant_scope,omitempty"`
	IdempotencyLookupCandidates []*IdempotencyLookupCandidate `protobuf:"bytes,4,rep,name=idempotency_lookup_candidates,json=idempotencyLookupCandidates,proto3" json:"idempotency_lookup_candidates,omitempty"`
	LookupWriteVersion          uint32                        `protobuf:"varint,5,opt,name=lookup_write_version,json=lookupWriteVersion,proto3" json:"lookup_write_version,omitempty"`
	DigestCandidates            []*RequestDigestCandidate     `protobuf:"bytes,6,rep,name=digest_candidates,json=digestCandidates,proto3" json:"digest_candidates,omitempty"`
	DigestWriteVersion          uint32                        `protobuf:"varint,7,opt,name=digest_write_version,json=digestWriteVersion,proto3" json:"digest_write_version,omitempty"`
	Model                       string                        `protobuf:"bytes,8,opt,name=model,proto3" json:"model,omitempty"`
	SlotCost                    uint32                        `protobuf:"varint,9,opt,name=slot_cost,json=slotCost,proto3" json:"slot_cost,omitempty"`
	ExecutionBudgetMs           int64                         `protobuf:"varint,10,opt,name=execution_budget_ms,json=executionBudgetMs,proto3" json:"execution_budget_ms,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *ScheduleRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ScheduleRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ScheduleRequest) GetTenantScope() []byte {
	if x != nil {
		return x.TenantScope
	}
	return nil
}

func (x *ScheduleRequest) GetIdempotencyLookupCandidates() []*IdempotencyLookupCandidate {
	if x != nil {
		return x.IdempotencyLookupCandidates
	}
	return nil
}

func (x *ScheduleRequest) GetLookupWriteVersion() uint32 {
	if x != nil {
		return x.LookupWriteVersion
	}
	return 0
}

func (x *ScheduleRequest) GetDigestCandidates() []*RequestDigestCandidate {
	if x != nil {
		return x.DigestCandidates
	}
	return nil
}

func (x *ScheduleRequest) GetDigestWriteVersion() uint32 {
	if x != nil {
		return x.DigestWriteVersion
	}
	return 0
}

func (x *ScheduleRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ScheduleRequest) GetSlotCost() uint32 {
	if x != nil {
		return x.SlotCost
	}
	return 0
}

func (x *ScheduleRequest) GetExecutionBudgetMs() int64 {
	if x != nil {
		return x.ExecutionBudgetMs
	}
	return 0
}

type ReservationRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Capability    []byte                 `protobuf:"bytes,3,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservationRef) Reset() {
	*x = ReservationRef{}
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationRef) ProtoMessage() {}

func (x *ReservationRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationRef.ProtoReflect.Descriptor instead.
func (*ReservationRef) Descriptor() ([]byte, []int) {
	return file_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *ReservationRef) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReservationRef) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ReservationRef) GetCapability() []byte {
	if x != nil {
		return x.Capability
	}
	return nil
}

type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *ReservationRef        `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *Reservation) GetRef() *ReservationRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type ScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *Reservation           `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *ScheduleResponse) GetReservation() *Reservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type PrepareDispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *ReservationRef        `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareDispatchRequest) Reset() {
	*x = PrepareDispatchRequest{}
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDispatchRequest) ProtoMessage() {}

func (x *PrepareDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareDispatchRequest.ProtoReflect.Descriptor instead.
func (*PrepareDispatchRequest) Descriptor() ([]byte, []int) {
	return file_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *PrepareDispatchRequest) GetRef() *ReservationRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type WorkloadIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	LogicalEngine string                 `protobuf:"bytes,3,opt,name=logical_engine,json=logicalEngine,proto3" json:"logical_engine,omitempty"`
	PodUid        string                 `protobuf:"bytes,4,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	EndpointEpoch uint64                 `protobuf:"varint,5,opt,name=endpoint_epoch,json=endpointEpoch,proto3" json:"endpoint_epoch,omitempty"`
	RecoveryEpoch uint64                 `protobuf:"varint,6,opt,name=recovery_epoch,json=recoveryEpoch,proto3" json:"recovery_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadIdentity) Reset() {
	*x = WorkloadIdentity{}
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadIdentity) ProtoMessage() {}

func (x *WorkloadIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadIdentity.ProtoReflect.Descriptor instead.
func (*WorkloadIdentity) Descriptor() ([]byte, []int) {
	return file_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *WorkloadIdentity) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *WorkloadIdentity) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WorkloadIdentity) GetLogicalEngine() string {
	if x != nil {
		return x.LogicalEngine
	}
	return ""
}

func (x *WorkloadIdentity) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *WorkloadIdentity) GetEndpointEpoch() uint64 {
	if x != nil {
		return x.EndpointEpoch
	}
	return 0
}

func (x *WorkloadIdentity) GetRecoveryEpoch() uint64 {
	if x != nil {
		return x.RecoveryEpoch
	}
	return 0
}

type DispatchTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Identity      *WorkloadIdentity      `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchTarget) Reset() {
	*x = DispatchTarget{}
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTarget) ProtoMessage() {}

func (x *DispatchTarget) ProtoReflect() protoreflect.Message {
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTarget.ProtoReflect.Descriptor instead.
func (*DispatchTarget) Descriptor() ([]byte, []int) {
	return file_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *DispatchTarget) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *DispatchTarget) GetIdentity() *WorkloadIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type PrepareDispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *DispatchTarget        `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareDispatchResponse) Reset() {
	*x = PrepareDispatchResponse{}
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareDispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareDispatchResponse) ProtoMessage() {}

func (x *PrepareDispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareDispatchResponse.ProtoReflect.Descriptor instead.
func (*PrepareDispatchResponse) Descriptor() ([]byte, []int) {
	return file_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *PrepareDispatchResponse) GetTarget() *DispatchTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

type GiveUpBeforeDispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *ReservationRef        `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Reason        GiveUpReason           `protobuf:"varint,2,opt,name=reason,proto3,enum=prudentia.scheduler.v1.GiveUpReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiveUpBeforeDispatchRequest) Reset() {
	*x = GiveUpBeforeDispatchRequest{}
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiveUpBeforeDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveUpBeforeDispatchRequest) ProtoMessage() {}

func (x *GiveUpBeforeDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveUpBeforeDispatchRequest.ProtoReflect.Descriptor instead.
func (*GiveUpBeforeDispatchRequest) Descriptor() ([]byte, []int) {
	return file_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *GiveUpBeforeDispatchRequest) GetRef() *ReservationRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *GiveUpBeforeDispatchRequest) GetReason() GiveUpReason {
	if x != nil {
		return x.Reason
	}
	return GiveUpReason_GIVE_UP_REASON_UNSPECIFIED
}

type FinalizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *ReservationRef        `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Proof         TerminalProof          `protobuf:"varint,2,opt,name=proof,proto3,enum=prudentia.scheduler.v1.TerminalProof" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeRequest) Reset() {
	*x = FinalizeRequest{}
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeRequest) ProtoMessage() {}

func (x *FinalizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeRequest.ProtoReflect.Descriptor instead.
func (*FinalizeRequest) Descriptor() ([]byte, []int) {
	return file_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{11}
}

func (x *FinalizeRequest) GetRef() *ReservationRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *FinalizeRequest) GetProof() TerminalProof {
	if x != nil {
		return x.Proof
	}
	return TerminalProof_TERMINAL_PROOF_UNSPECIFIED
}

type MarkAmbiguousRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *ReservationRef        `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Cause         AmbiguousCause         `protobuf:"varint,2,opt,name=cause,proto3,enum=prudentia.scheduler.v1.AmbiguousCause" json:"cause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAmbiguousRequest) Reset() {
	*x = MarkAmbiguousRequest{}
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAmbiguousRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAmbiguousRequest) ProtoMessage() {}

func (x *MarkAmbiguousRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAmbiguousRequest.ProtoReflect.Descriptor instead.
func (*MarkAmbiguousRequest) Descriptor() ([]byte, []int) {
	return file_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *MarkAmbiguousRequest) GetRef() *ReservationRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *MarkAmbiguousRequest) GetCause() AmbiguousCause {
	if x != nil {
		return x.Cause
	}
	return AmbiguousCause_AMBIGUOUS_CAUSE_UNSPECIFIED
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_scheduler_v1_scheduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{13}
}

var File_api_scheduler_v1_scheduler_proto protoreflect.FileDescriptor

const file_api_scheduler_v1_scheduler_proto_rawDesc = "" +
	"\n" +
	" api/scheduler/v1/scheduler.proto\x12\x16prudentia.scheduler.v1\"d\n" +
	"\x1aIdempotencyLookupCandidate\x12%\n" +
	"\x0epepper_version\x18\x01 \x01(\rR\rpepperVersion\x12\x1f\n" +
	"\vhmac_sha256\x18\x02 \x01(\fR\n" +
	"hmacSha256\"`\n" +
	"\x16RequestDigestCandidate\x12%\n" +
	"\x0edigest_version\x18\x01 \x01(\rR\rdigestVersion\x12\x1f\n" +
	"\vhmac_sha256\x18\x02 \x01(\fR\n" +
	"hmacSha256\"\x8e\x04\n" +
	"\x0fScheduleRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12!\n" +
	"\ftenant_scope\x18\x03 \x01(\fR\vtenantScope\x12v\n" +
	"\x1didempotency_lookup_candidates\x18\x04 \x03(\v22.prudentia.scheduler.v1.IdempotencyLookupCandidateR\x1bidempotencyLookupCandidates\x120\n" +
	"\x14lookup_write_version\x18\x05 \x01(\rR\x12lookupWriteVersion\x12[\n" +
	"\x11digest_candidates\x18\x06 \x03(\v2..prudentia.scheduler.v1.RequestDigestCandidateR\x10digestCandidates\x120\n" +
	"\x14digest_write_version\x18\a \x01(\rR\x12digestWriteVersion\x12\x14\n" +
	"\x05model\x18\b \x01(\tR\x05model\x12\x1b\n" +
	"\tslot_cost\x18\t \x01(\rR\bslotCost\x12.\n" +
	"\x13execution_budget_ms\x18\n" +
	" \x01(\x03R\x11executionBudgetMs\"w\n" +
	"\x0eReservationRef\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12\x1e\n" +
	"\n" +
	"capability\x18\x03 \x01(\fR\n" +
	"capability\"G\n" +
	"\vReservation\x128\n" +
	"\x03ref\x18\x01 \x01(\v2&.prudentia.scheduler.v1.ReservationRefR\x03ref\"Y\n" +
	"\x10ScheduleResponse\x12E\n" +
	"\vreservation\x18\x01 \x01(\v2#.prudentia.scheduler.v1.ReservationR\vreservation\"R\n" +
	"\x16PrepareDispatchRequest\x128\n" +
	"\x03ref\x18\x01 \x01(\v2&.prudentia.scheduler.v1.ReservationRefR\x03ref\"\xd8\x01\n" +
	"\x10WorkloadIdentity\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12%\n" +
	"\x0elogical_engine\x18\x03 \x01(\tR\rlogicalEngine\x12\x17\n" +
	"\apod_uid\x18\x04 \x01(\tR\x06podUid\x12%\n" +
	"\x0eendpoint_epoch\x18\x05 \x01(\x04R\rendpointEpoch\x12%\n" +
	"\x0erecovery_epoch\x18\x06 \x01(\x04R\rrecoveryEpoch\"r\n" +
	"\x0eDispatchTarget\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12D\n" +
	"\bidentity\x18\x02 \x01(\v2(.prudentia.scheduler.v1.WorkloadIdentityR\bidentity\"Y\n" +
	"\x17PrepareDispatchResponse\x12>\n" +
	"\x06target\x18\x01 \x01(\v2&.prudentia.scheduler.v1.DispatchTargetR\x06target\"\x95\x01\n" +
	"\x1bGiveUpBeforeDispatchRequest\x128\n" +
	"\x03ref\x18\x01 \x01(\v2&.prudentia.scheduler.v1.ReservationRefR\x03ref\x12<\n" +
	"\x06reason\x18\x02 \x01(\x0e2$.prudentia.scheduler.v1.GiveUpReasonR\x06reason\"\x88\x01\n" +
	"\x0fFinalizeRequest\x128\n" +
	"\x03ref\x18\x01 \x01(\v2&.prudentia.scheduler.v1.ReservationRefR\x03ref\x12;\n" +
	"\x05proof\x18\x02 \x01(\x0e2%.prudentia.scheduler.v1.TerminalProofR\x05proof\"\x8e\x01\n" +
	"\x14MarkAmbiguousRequest\x128\n" +
	"\x03ref\x18\x01 \x01(\v2&.prudentia.scheduler.v1.ReservationRefR\x03ref\x12<\n" +
	"\x05cause\x18\x02 \x01(\x0e2&.prudentia.scheduler.v1.AmbiguousCauseR\x05cause\"\a\n" +
	"\x05Empty*\x94\x01\n" +
	"\fGiveUpReason\x12\x1e\n" +
	"\x1aGIVE_UP_REASON_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17GIVE_UP_REASON_CANCELED\x10\x01\x12!\n" +
	"\x1dGIVE_UP_REASON_BUDGET_EXPIRED\x10\x02\x12$\n" +
	" GIVE_UP_REASON_RERANKS_EXHAUSTED\x10\x03*p\n" +
	"\rTerminalProof\x12\x1e\n" +
	"\x1aTERMINAL_PROOF_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eTERMINAL_PROOF_PROVIDER_FINISH\x10\x01\x12\x1b\n" +
	"\x17TERMINAL_PROOF_NOT_SENT\x10\x02*\x8c\x01\n" +
	"\x0eAmbiguousCause\x12\x1f\n" +
	"\x1bAMBIGUOUS_CAUSE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19AMBIGUOUS_CAUSE_TRANSPORT\x10\x01\x12\x1c\n" +
	"\x18AMBIGUOUS_CAUSE_CANCELED\x10\x02\x12\x1c\n" +
	"\x18AMBIGUOUS_CAUSE_PROTOCOL\x10\x032\x83\x04\n" +
	"\x10SchedulerService\x12]\n" +
	"\bSchedule\x12'.prudentia.scheduler.v1.ScheduleRequest\x1a(.prudentia.scheduler.v1.ScheduleResponse\x12r\n" +
	"\x0fPrepareDispatch\x12..prudentia.scheduler.v1.PrepareDispatchRequest\x1a/.prudentia.scheduler.v1.PrepareDispatchResponse\x12j\n" +
	"\x14GiveUpBeforeDispatch\x123.prudentia.scheduler.v1.GiveUpBeforeDispatchRequest\x1a\x1d.prudentia.scheduler.v1.Empty\x12R\n" +
	"\bFinalize\x12'.prudentia.scheduler.v1.FinalizeRequest\x1a\x1d.prudentia.scheduler.v1.Empty\x12\\\n" +
	"\rMarkAmbiguous\x12,.prudentia.scheduler.v1.MarkAmbiguousRequest\x1a\x1d.prudentia.scheduler.v1.EmptyBDZBgithub.com/BizerNotNull/474-Prudentia/api/scheduler/v1;schedulerv1b\x06proto3"

var (
	file_api_scheduler_v1_scheduler_proto_rawDescOnce sync.Once
	file_api_scheduler_v1_scheduler_proto_rawDescData []byte
)

func file_api_scheduler_v1_scheduler_proto_rawDescGZIP() []byte {
	file_api_scheduler_v1_scheduler_proto_rawDescOnce.Do(func() {
		file_api_scheduler_v1_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_scheduler_v1_scheduler_proto_rawDesc), len(file_api_scheduler_v1_scheduler_proto_rawDesc)))
	})
	return file_api_scheduler_v1_scheduler_proto_rawDescData
}

var file_api_scheduler_v1_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_scheduler_v1_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_scheduler_v1_scheduler_proto_goTypes = []any{
	(GiveUpReason)(0),                   // 0: prudentia.scheduler.v1.GiveUpReason
	(TerminalProof)(0),                  // 1: prudentia.scheduler.v1.TerminalProof
	(AmbiguousCause)(0),                 // 2: prudentia.scheduler.v1.AmbiguousCause
	(*IdempotencyLookupCandidate)(nil),  // 3: prudentia.scheduler.v1.IdempotencyLookupCandidate
	(*RequestDigestCandidate)(nil),      // 4: prudentia.scheduler.v1.RequestDigestCandidate
	(*ScheduleRequest)(nil),             // 5: prudentia.scheduler.v1.ScheduleRequest
	(*ReservationRef)(nil),              // 6: prudentia.scheduler.v1.ReservationRef
	(*Reservation)(nil),                 // 7: prudentia.scheduler.v1.Reservation
	(*ScheduleResponse)(nil),            // 8: prudentia.scheduler.v1.ScheduleResponse
	(*PrepareDispatchRequest)(nil),      // 9: prudentia.scheduler.v1.PrepareDispatchRequest
	(*WorkloadIdentity)(nil),            // 10: prudentia.scheduler.v1.WorkloadIdentity
	(*DispatchTarget)(nil),              // 11: prudentia.scheduler.v1.DispatchTarget
	(*PrepareDispatchResponse)(nil),     // 12: prudentia.scheduler.v1.PrepareDispatchResponse
	(*GiveUpBeforeDispatchRequest)(nil), // 13: prudentia.scheduler.v1.GiveUpBeforeDispatchRequest
	(*FinalizeRequest)(nil),             // 14: prudentia.scheduler.v1.FinalizeRequest
	(*MarkAmbiguousRequest)(nil),        // 15: prudentia.scheduler.v1.MarkAmbiguousRequest
	(*Empty)(nil),                       // 16: prudentia.scheduler.v1.Empty
}
var file_api_scheduler_v1_scheduler_proto_depIdxs = []int32{
	3,  // 0: prudentia.scheduler.v1.ScheduleRequest.idempotency_lookup_candidates:type_name -> prudentia.scheduler.v1.IdempotencyLookupCandidate
	4,  // 1: prudentia.scheduler.v1.ScheduleRequest.digest_candidates:type_name -> prudentia.scheduler.v1.RequestDigestCandidate
	6,  // 2: prudentia.scheduler.v1.Reservation.ref:type_name -> prudentia.scheduler.v1.ReservationRef
	7,  // 3: prudentia.scheduler.v1.ScheduleResponse.reservation:type_name -> prudentia.scheduler.v1.Reservation
	6,  // 4: prudentia.scheduler.v1.PrepareDispatchRequest.ref:type_name -> prudentia.scheduler.v1.ReservationRef
	10, // 5: prudentia.scheduler.v1.DispatchTarget.identity:type_name -> prudentia.scheduler.v1.WorkloadIdentity
	11, // 6: prudentia.scheduler.v1.PrepareDispatchResponse.target:type_name -> prudentia.scheduler.v1.DispatchTarget
	6,  // 7: prudentia.scheduler.v1.GiveUpBeforeDispatchRequest.ref:type_name -> prudentia.scheduler.v1.ReservationRef
	0,  // 8: prudentia.scheduler.v1.GiveUpBeforeDispatchRequest.reason:type_name -> prudentia.scheduler.v1.GiveUpReason
	6,  // 9: prudentia.scheduler.v1.FinalizeRequest.ref:type_name -> prudentia.scheduler.v1.ReservationRef
	1,  // 10: prudentia.scheduler.v1.FinalizeRequest.proof:type_name -> prudentia.scheduler.v1.TerminalProof
	6,  // 11: prudentia.scheduler.v1.MarkAmbiguousRequest.ref:type_name -> prudentia.scheduler.v1.ReservationRef
	2,  // 12: prudentia.scheduler.v1.MarkAmbiguousRequest.cause:type_name -> prudentia.scheduler.v1.AmbiguousCause
	5,  // 13: prudentia.scheduler.v1.SchedulerService.Schedule:input_type -> prudentia.scheduler.v1.ScheduleRequest
	9,  // 14: prudentia.scheduler.v1.SchedulerService.PrepareDispatch:input_type -> prudentia.scheduler.v1.PrepareDispatchRequest
	13, // 15: prudentia.scheduler.v1.SchedulerService.GiveUpBeforeDispatch:input_type -> prudentia.scheduler.v1.GiveUpBeforeDispatchRequest
	14, // 16: prudentia.scheduler.v1.SchedulerService.Finalize:input_type -> prudentia.scheduler.v1.FinalizeRequest
	15, // 17: prudentia.scheduler.v1.SchedulerService.MarkAmbiguous:input_type -> prudentia.scheduler.v1.MarkAmbiguousRequest
	8,  // 18: prudentia.scheduler.v1.SchedulerService.Schedule:output_type -> prudentia.scheduler.v1.ScheduleResponse
	12, // 19: prudentia.scheduler.v1.SchedulerService.PrepareDispatch:output_type -> prudentia.scheduler.v1.PrepareDispatchResponse
	16, // 20: prudentia.scheduler.v1.SchedulerService.GiveUpBeforeDispatch:output_type -> prudentia.scheduler.v1.Empty
	16, // 21: prudentia.scheduler.v1.SchedulerService.Finalize:output_type -> prudentia.scheduler.v1.Empty
	16, // 22: prudentia.scheduler.v1.SchedulerService.MarkAmbiguous:output_type -> prudentia.scheduler.v1.Empty
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_scheduler_v1_scheduler_proto_init() }
func file_api_scheduler_v1_scheduler_proto_init() {
	if File_api_scheduler_v1_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_scheduler_v1_scheduler_proto_rawDesc), len(file_api_scheduler_v1_scheduler_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_scheduler_v1_scheduler_proto_goTypes,
		DependencyIndexes: file_api_scheduler_v1_scheduler_proto_depIdxs,
		EnumInfos:         file_api_scheduler_v1_scheduler_proto_enumTypes,
		MessageInfos:      file_api_scheduler_v1_scheduler_proto_msgTypes,
	}.Build()
	File_api_scheduler_v1_scheduler_proto = out.File
	file_api_scheduler_v1_scheduler_proto_goTypes = nil
	file_api_scheduler_v1_scheduler_proto_depIdxs = nil
}
