// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: api/scheduler/v1/scheduler.proto

package schedulerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchedulerService_Schedule_FullMethodName             = "/prudentia.scheduler.v1.SchedulerService/Schedule"
	SchedulerService_PrepareDispatch_FullMethodName      = "/prudentia.scheduler.v1.SchedulerService/PrepareDispatch"
	SchedulerService_GiveUpBeforeDispatch_FullMethodName = "/prudentia.scheduler.v1.SchedulerService/GiveUpBeforeDispatch"
	SchedulerService_Finalize_FullMethodName             = "/prudentia.scheduler.v1.SchedulerService/Finalize"
	SchedulerService_MarkAmbiguous_FullMethodName        = "/prudentia.scheduler.v1.SchedulerService/MarkAmbiguous"
)

// SchedulerServiceClient is the client API for SchedulerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulerServiceClient interface {
	Schedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error)
	PrepareDispatch(ctx context.Context, in *PrepareDispatchRequest, opts ...grpc.CallOption) (*PrepareDispatchResponse, error)
	GiveUpBeforeDispatch(ctx context.Context, in *GiveUpBeforeDispatchRequest, opts ...grpc.CallOption) (*Empty, error)
	Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (*Empty, error)
	MarkAmbiguous(ctx context.Context, in *MarkAmbiguousRequest, opts ...grpc.CallOption) (*Empty, error)
}

type schedulerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerServiceClient(cc grpc.ClientConnInterface) SchedulerServiceClient {
	return &schedulerServiceClient{cc}
}

func (c *schedulerServiceClient) Schedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, SchedulerService_Schedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) PrepareDispatch(ctx context.Context, in *PrepareDispatchRequest, opts ...grpc.CallOption) (*PrepareDispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareDispatchResponse)
	err := c.cc.Invoke(ctx, SchedulerService_PrepareDispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) GiveUpBeforeDispatch(ctx context.Context, in *GiveUpBeforeDispatchRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SchedulerService_GiveUpBeforeDispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SchedulerService_Finalize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerServiceClient) MarkAmbiguous(ctx context.Context, in *MarkAmbiguousRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SchedulerService_MarkAmbiguous_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServiceServer is the server API for SchedulerService service.
// All implementations must embed UnimplementedSchedulerServiceServer
// for forward compatibility.
type SchedulerServiceServer interface {
	Schedule(context.Context, *ScheduleRequest) (*ScheduleResponse, error)
	PrepareDispatch(context.Context, *PrepareDispatchRequest) (*PrepareDispatchResponse, error)
	GiveUpBeforeDispatch(context.Context, *GiveUpBeforeDispatchRequest) (*Empty, error)
	Finalize(context.Context, *FinalizeRequest) (*Empty, error)
	MarkAmbiguous(context.Context, *MarkAmbiguousRequest) (*Empty, error)
	mustEmbedUnimplementedSchedulerServiceServer()
}

// UnimplementedSchedulerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulerServiceServer struct{}

func (UnimplementedSchedulerServiceServer) Schedule(context.Context, *ScheduleRequest) (*ScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Schedule not implemented")
}
func (UnimplementedSchedulerServiceServer) PrepareDispatch(context.Context, *PrepareDispatchRequest) (*PrepareDispatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareDispatch not implemented")
}
func (UnimplementedSchedulerServiceServer) GiveUpBeforeDispatch(context.Context, *GiveUpBeforeDispatchRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method GiveUpBeforeDispatch not implemented")
}
func (UnimplementedSchedulerServiceServer) Finalize(context.Context, *FinalizeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Finalize not implemented")
}
func (UnimplementedSchedulerServiceServer) MarkAmbiguous(context.Context, *MarkAmbiguousRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAmbiguous not implemented")
}
func (UnimplementedSchedulerServiceServer) mustEmbedUnimplementedSchedulerServiceServer() {}
func (UnimplementedSchedulerServiceServer) testEmbeddedByValue()                          {}

// UnsafeSchedulerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerServiceServer will
// result in compilation errors.
type UnsafeSchedulerServiceServer interface {
	mustEmbedUnimplementedSchedulerServiceServer()
}

func RegisterSchedulerServiceServer(s grpc.ServiceRegistrar, srv SchedulerServiceServer) {
	// If the following call panics, it indicates UnimplementedSchedulerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedulerService_ServiceDesc, srv)
}

func _SchedulerService_Schedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).Schedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_Schedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).Schedule(ctx, req.(*ScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_PrepareDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).PrepareDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_PrepareDispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).PrepareDispatch(ctx, req.(*PrepareDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_GiveUpBeforeDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GiveUpBeforeDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).GiveUpBeforeDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_GiveUpBeforeDispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).GiveUpBeforeDispatch(ctx, req.(*GiveUpBeforeDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_Finalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).Finalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_Finalize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).Finalize(ctx, req.(*FinalizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerService_MarkAmbiguous_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAmbiguousRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServiceServer).MarkAmbiguous(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerService_MarkAmbiguous_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServiceServer).MarkAmbiguous(ctx, req.(*MarkAmbiguousRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchedulerService_ServiceDesc is the grpc.ServiceDesc for SchedulerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prudentia.scheduler.v1.SchedulerService",
	HandlerType: (*SchedulerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Schedule",
			Handler:    _SchedulerService_Schedule_Handler,
		},
		{
			MethodName: "PrepareDispatch",
			Handler:    _SchedulerService_PrepareDispatch_Handler,
		},
		{
			MethodName: "GiveUpBeforeDispatch",
			Handler:    _SchedulerService_GiveUpBeforeDispatch_Handler,
		},
		{
			MethodName: "Finalize",
			Handler:    _SchedulerService_Finalize_Handler,
		},
		{
			MethodName: "MarkAmbiguous",
			Handler:    _SchedulerService_MarkAmbiguous_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/scheduler/v1/scheduler.proto",
}
