// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: api/admin/v1/capacity_debt_admin.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnsafeOverrideCapacityDebtRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	DebtId                string                 `protobuf:"bytes,1,opt,name=debt_id,json=debtId,proto3" json:"debt_id,omitempty"`
	ExpectedPodUid        string                 `protobuf:"bytes,2,opt,name=expected_pod_uid,json=expectedPodUid,proto3" json:"expected_pod_uid,omitempty"`
	ExpectedEndpointEpoch uint64                 `protobuf:"varint,3,opt,name=expected_endpoint_epoch,json=expectedEndpointEpoch,proto3" json:"expected_endpoint_epoch,omitempty"`
	// Must equal I_UNDERSTAND_THE_PROVIDER_MAY_STILL_BE_EXECUTING exactly.
	Confirmation string `protobuf:"bytes,4,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	// Bounded, nonempty, sanitized operational ticket and reason.
	Ticket string `protobuf:"bytes,5,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Reason string `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	// Version 1 defines the confirmation phrase and all field semantics.
	SchemaVersion uint32 `protobuf:"varint,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsafeOverrideCapacityDebtRequest) Reset() {
	*x = UnsafeOverrideCapacityDebtRequest{}
	mi := &file_api_admin_v1_capacity_debt_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsafeOverrideCapacityDebtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsafeOverrideCapacityDebtRequest) ProtoMessage() {}

func (x *UnsafeOverrideCapacityDebtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_admin_v1_capacity_debt_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsafeOverrideCapacityDebtRequest.ProtoReflect.Descriptor instead.
func (*UnsafeOverrideCapacityDebtRequest) Descriptor() ([]byte, []int) {
	return file_api_admin_v1_capacity_debt_admin_proto_rawDescGZIP(), []int{0}
}

func (x *UnsafeOverrideCapacityDebtRequest) GetDebtId() string {
	if x != nil {
		return x.DebtId
	}
	return ""
}

func (x *UnsafeOverrideCapacityDebtRequest) GetExpectedPodUid() string {
	if x != nil {
		return x.ExpectedPodUid
	}
	return ""
}

func (x *UnsafeOverrideCapacityDebtRequest) GetExpectedEndpointEpoch() uint64 {
	if x != nil {
		return x.ExpectedEndpointEpoch
	}
	return 0
}

func (x *UnsafeOverrideCapacityDebtRequest) GetConfirmation() string {
	if x != nil {
		return x.Confirmation
	}
	return ""
}

func (x *UnsafeOverrideCapacityDebtRequest) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *UnsafeOverrideCapacityDebtRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UnsafeOverrideCapacityDebtRequest) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

var File_api_admin_v1_capacity_debt_admin_proto protoreflect.FileDescriptor

const file_api_admin_v1_capacity_debt_admin_proto_rawDesc = "" +
	"\n" +
	"&api/admin/v1/capacity_debt_admin.proto\x12\x12prudentia.admin.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x99\x02\n" +
	"!UnsafeOverrideCapacityDebtRequest\x12\x17\n" +
	"\adebt_id\x18\x01 \x01(\tR\x06debtId\x12(\n" +
	"\x10expected_pod_uid\x18\x02 \x01(\tR\x0eexpectedPodUid\x126\n" +
	"\x17expected_endpoint_epoch\x18\x03 \x01(\x04R\x15expectedEndpointEpoch\x12\"\n" +
	"\fconfirmation\x18\x04 \x01(\tR\fconfirmation\x12\x16\n" +
	"\x06ticket\x18\x05 \x01(\tR\x06ticket\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12%\n" +
	"\x0eschema_version\x18\a \x01(\rR\rschemaVersion2\x87\x01\n" +
	"\x18CapacityDebtAdminService\x12k\n" +
	"\x1aUnsafeOverrideCapacityDebt\x125.prudentia.admin.v1.UnsafeOverrideCapacityDebtRequest\x1a\x16.google.protobuf.EmptyB<Z:github.com/BizerNotNull/474-Prudentia/api/admin/v1;adminv1b\x06proto3"

var (
	file_api_admin_v1_capacity_debt_admin_proto_rawDescOnce sync.Once
	file_api_admin_v1_capacity_debt_admin_proto_rawDescData []byte
)

func file_api_admin_v1_capacity_debt_admin_proto_rawDescGZIP() []byte {
	file_api_admin_v1_capacity_debt_admin_proto_rawDescOnce.Do(func() {
		file_api_admin_v1_capacity_debt_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_admin_v1_capacity_debt_admin_proto_rawDesc), len(file_api_admin_v1_capacity_debt_admin_proto_rawDesc)))
	})
	return file_api_admin_v1_capacity_debt_admin_proto_rawDescData
}

var file_api_admin_v1_capacity_debt_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_admin_v1_capacity_debt_admin_proto_goTypes = []any{
	(*UnsafeOverrideCapacityDebtRequest)(nil), // 0: prudentia.admin.v1.UnsafeOverrideCapacityDebtRequest
	(*emptypb.Empty)(nil),                     // 1: google.protobuf.Empty
}
var file_api_admin_v1_capacity_debt_admin_proto_depIdxs = []int32{
	0, // 0: prudentia.admin.v1.CapacityDebtAdminService.UnsafeOverrideCapacityDebt:input_type -> prudentia.admin.v1.UnsafeOverrideCapacityDebtRequest
	1, // 1: prudentia.admin.v1.CapacityDebtAdminService.UnsafeOverrideCapacityDebt:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_admin_v1_capacity_debt_admin_proto_init() }
func file_api_admin_v1_capacity_debt_admin_proto_init() {
	if File_api_admin_v1_capacity_debt_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_admin_v1_capacity_debt_admin_proto_rawDesc), len(file_api_admin_v1_capacity_debt_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_admin_v1_capacity_debt_admin_proto_goTypes,
		DependencyIndexes: file_api_admin_v1_capacity_debt_admin_proto_depIdxs,
		MessageInfos:      file_api_admin_v1_capacity_debt_admin_proto_msgTypes,
	}.Build()
	File_api_admin_v1_capacity_debt_admin_proto = out.File
	file_api_admin_v1_capacity_debt_admin_proto_goTypes = nil
	file_api_admin_v1_capacity_debt_admin_proto_depIdxs = nil
}
