// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: api/admin/v1/capacity_debt_admin.proto

package adminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CapacityDebtAdminService_UnsafeOverrideCapacityDebt_FullMethodName = "/prudentia.admin.v1.CapacityDebtAdminService/UnsafeOverrideCapacityDebt"
)

// CapacityDebtAdminServiceClient is the client API for CapacityDebtAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// This service is exposed only on the separately addressed admin mTLS listener.
type CapacityDebtAdminServiceClient interface {
	UnsafeOverrideCapacityDebt(ctx context.Context, in *UnsafeOverrideCapacityDebtRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type capacityDebtAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCapacityDebtAdminServiceClient(cc grpc.ClientConnInterface) CapacityDebtAdminServiceClient {
	return &capacityDebtAdminServiceClient{cc}
}

func (c *capacityDebtAdminServiceClient) UnsafeOverrideCapacityDebt(ctx context.Context, in *UnsafeOverrideCapacityDebtRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CapacityDebtAdminService_UnsafeOverrideCapacityDebt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapacityDebtAdminServiceServer is the server API for CapacityDebtAdminService service.
// All implementations must embed UnimplementedCapacityDebtAdminServiceServer
// for forward compatibility.
//
// This service is exposed only on the separately addressed admin mTLS listener.
type CapacityDebtAdminServiceServer interface {
	UnsafeOverrideCapacityDebt(context.Context, *UnsafeOverrideCapacityDebtRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedCapacityDebtAdminServiceServer()
}

// UnimplementedCapacityDebtAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapacityDebtAdminServiceServer struct{}

func (UnimplementedCapacityDebtAdminServiceServer) UnsafeOverrideCapacityDebt(context.Context, *UnsafeOverrideCapacityDebtRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnsafeOverrideCapacityDebt not implemented")
}
func (UnimplementedCapacityDebtAdminServiceServer) mustEmbedUnimplementedCapacityDebtAdminServiceServer() {
}
func (UnimplementedCapacityDebtAdminServiceServer) testEmbeddedByValue() {}

// UnsafeCapacityDebtAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapacityDebtAdminServiceServer will
// result in compilation errors.
type UnsafeCapacityDebtAdminServiceServer interface {
	mustEmbedUnimplementedCapacityDebtAdminServiceServer()
}

func RegisterCapacityDebtAdminServiceServer(s grpc.ServiceRegistrar, srv CapacityDebtAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedCapacityDebtAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CapacityDebtAdminService_ServiceDesc, srv)
}

func _CapacityDebtAdminService_UnsafeOverrideCapacityDebt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsafeOverrideCapacityDebtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityDebtAdminServiceServer).UnsafeOverrideCapacityDebt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapacityDebtAdminService_UnsafeOverrideCapacityDebt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityDebtAdminServiceServer).UnsafeOverrideCapacityDebt(ctx, req.(*UnsafeOverrideCapacityDebtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CapacityDebtAdminService_ServiceDesc is the grpc.ServiceDesc for CapacityDebtAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CapacityDebtAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prudentia.admin.v1.CapacityDebtAdminService",
	HandlerType: (*CapacityDebtAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnsafeOverrideCapacityDebt",
			Handler:    _CapacityDebtAdminService_UnsafeOverrideCapacityDebt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/admin/v1/capacity_debt_admin.proto",
}
